spring:
  application:
    name: Car-Rental
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql
logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.engine.jdbc.spi: DEBUG
    com.mysql.cj.jdbc: TRACE
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

---
#Profil dev
spring:
  config:
    activate:
      on-profile: dev
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5s

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

---
#Profil docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/car_rental
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
      timeout: 5s
---

server:
  servlet:
    session:
      timeout: 15m
  port: 8080
