spring:
  application:
    name: Car-Rental
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      data-locations: classpath:sql/data.sql
logging:
  level:
    pl.coderslab.carrental: INFO
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

server:
  servlet:
    session:
      timeout: 15m

stripe:
  secret-key: ${STRIPE_SECRET_KEY}