### GET all
GET localhost:8080/api/cars

###
GET localhost:8080/api/cars

###(brand)
GET localhost:8080/api/cars?brand=BMW

###(status)
GET localhost:8080/api/cars?carStatus=RENTED

###(filtered by both status and brand)
GET localhost:8080/api/cars?carStatus=AVAILABLE&brand=BMW

###(creating a car, status will be available regardless of data input in JSON, required due to validation)
POST localhost:8080/api/admin/car
Content-Type: application/json

{
  "brand": {
    "id": 1
  },
  "carStatus": "Rented",
  "model": "220",
  "year": 2017,
  "pricePerDay": 450
}

###(creating a car non existing brand)
POST localhost:8080/api/admin/car
Content-Type: application/json

{
  "brand": {
    "id": 111
  },
  "carStatus": "Available",
  "model": "Tipo",
  "year": 2020,
  "pricePerDay": 30
}

### - non existing car and brand - should throw and handle exception
PUT localhost:8080/api/admin/car?id=1
Content-Type: application/json

{
  "brand": {
    "id": 2
  },
  "carStatus": "Available",
  "model": "Updated",
  "year": 2011,
  "pricePerDay": 1200
}

### - update with existing brand
PUT localhost:8080/api/admin/car?id=2
Content-Type: application/json

{
  "brand": {
    "id": 2
  },
  "carStatus": "Available",
  "model": "Updated",
  "year": 2011,
  "pricePerDay": 1200
}

### existing car
DELETE localhost:8080/api/admin/car?id=2

### non exsiting car deletion
DELETE localhost:8080/api/admin/car?id=123
