### GET all
GET localhost:8080/api/cars

###(brand)
GET localhost:8080/api/cars?brand=BMW

###(status)
GET localhost:8080/api/cars?carStatus=RENTED

###(filtered by both status and brand)
GET localhost:8080/api/cars?carStatus=AVAILABLE&brand=BMW

###(car with id null)
GET localhost:8080/api/car?id=null

###(creating a car with no existing brand)
POST localhost:8080/api/admin/car
Content-Type: application/json

{
  "brand": {
    "id": 1
  },
  "carStatus": "Available",
  "model": "Tipo",
  "year": 2020,
  "pricePerDay": 1200
}

###(creating a car)
POST localhost:8080/api/admin/car
Content-Type: application/json

{
  "brand": {
    "id": 111
  },
  "carStatus": "Available",
  "model": "Tipo",
  "year": 2020,
  "pricePerDay": 1200
}

### - non existing brand - should throw and handle exception
PUT localhost:8080/api/admin/car?id=2
Content-Type: application/json

{
  "brand": {
    "id": 455
  },
  "carStatus": "Available",
  "model": "Updated",
  "year": 2011,
  "pricePerDay": 1200
}

### - update with existing brand
PUT localhost:8080/api/admin/car?id=2
Content-Type: application/json

{
  "brand": {
    "id": 4
  },
  "carStatus": "Available",
  "model": "Updated",
  "year": 2011,
  "pricePerDay": 1200
}


### existing car
DELETE localhost:8080/api/admin/car?id=18

### non exsiting car deletion
DELETE localhost:8080/api/admin/car?id=123