### Get filtered by period of time(issue date of invoice)
GET localhost:8080/api/invoices?start=2025-09-01&end=2025-10-30

### Get invoice by ID
GET localhost:8080/api/admin/invoice?id=1

###Creation of invoice (happy path)
POST localhost:8080/api/admin/invoice
Content-Type: application/json

{
  "reservationId": 3
}

###Creation of invoice (duplicated)
POST localhost:8080/api/admin/invoice
Content-Type: application/json

{
  "reservationId": 1
}

###Creating for non exisitng reservation
POST localhost:8080/api/admin/invoice
Content-Type: application/json

{
  "reservationId": 2333
}

###pdf
GET localhost:8080/api/invoices/pdf?id=5

###Deletion(happy path)
DELETE localhost:8080/api/admin/invoice?id=2

###Deletion(non existing value)
DELETE localhost:8080/api/admin/invoice?id=12323

###Update exisitng (refreshes all data based on related entities)
PUT localhost:8080/api/admin/invoice?id=4

