### GET all without filters
GET localhost:8080/api/payments

### GET with filters
GET localhost:8080/api/payments?paymentMethod=BANK_TRANSFER&paymentStatus=APPROVED&reservationId=2

###
POST localhost:8080/api/pay
Content-Type: application/json

{
  "reservationId": 3,
  "paymentMethod": "Bank Transfer",
  "paymentStatus": "Approved"
}

###
PUT localhost:8080/api/payment-status?id=3&paymentStatus=FUNDS_BEING_REFUNDED

###
GET localhost:8080/api/payments?reservationId=1

