### GET all without filters
GET localhost:8080/api/payments

### GET with filters
GET localhost:8080/api/payments?paymentMethod=CARD

###
POST localhost:8080/api/pay
Content-Type: application/json

{
  "reservationId": 1,
  "paymentMethod": "Bank Transfer",
  "paymentStatus": "Approved"
}

###
PUT localhost:8080/api/payment-status?id=1&paymentStatus=FUNDS_BEING_REFUNDED

###
GET localhost:8080/api/payments?reservationId=19

###
GET localhost:8080/api/payments

