###
GET localhost:8080/api/reservations

###Field confirmed will always be set to false while creating
POST localhost:8080/api/reservation
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-09-29",
  "dateTo": "2025-09-30",
  "userId": 4,
  "confirmed": true
}

###
PUT localhost:8080/api/reservation?id=9
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-09-24",
  "dateTo": "2025-09-27",
  "userId": 4,
  "confirmed": false
}

###
PUT localhost:8080/api/admin/reservation-status?id=1&status=false

### - removing exsiting
DELETE localhost:8080/api/admin/reservation?id=2

### - removing not exsiting
DELETE localhost:8080/api/admin/reservation?id=20

