###
GET localhost:8080/api/reservations

###Field confirmed will always be set to false while creating
POST localhost:8080/api/reservation
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-10-15",
  "dateTo": "2025-10-15",
  "userId": 3,
  "confirmed": false
}

###
PUT localhost:8080/api/reservation?id=1
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-09-30",
  "dateTo": "2025-10-11",
  "userId": 3,
  "confirmed": false
}

###
PUT localhost:8080/api/admin/reservation-status?id=1&status=true

### - removing exsiting
DELETE localhost:8080/api/admin/reservation?id=1

### - removing not exsiting
DELETE localhost:8080/api/admin/reservation?id=20

