###
GET localhost:8080/api/reservations

###Field confirmed will always be set to false while creating
POST localhost:8080/api/reservation
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-09-08",
  "dateTo": "2025-09-12",
  "userId": 1,
  "confirmed": true
}

###
PUT localhost:8080/api/reservation?id=27
Content-Type: application/json

{
  "carId": 1,
  "dateFrom": "2025-09-08",
  "dateTo": "2025-09-13",
  "userId": 1,
  "confirmed": false
}

###
PUT localhost:8080/api/admin/reservation-status?id=23&status=true

### - removing exsiting
DELETE localhost:8080/api/admin/reservation?id=20

### - removing not exsiting
DELETE localhost:8080/api/admin/reservation?id=20

