### GET all
GET localhost:8080/api/reviews

### GET request to example server
GET localhost:8080/api/review?id=1

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 1,
  "description": "First review",
  "rating": 5,
  "pseudonym": "Janusz P."
}

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 111,
  "description": "Review xxxxx",
  "rating": 5,
  "pseudonym": "Janek B."
}

###
PUT localhost:8080/api/review?id=1
Content-Type: application/json

{
  "reservationId": 1,
  "description": "Updatowana review",
  "rating": 3,
  "pseudonym": "Janusz P."
}

###
DELETE localhost:8080/api/review?id=1