### GET all
GET localhost:8080/api/reviews

### GET request to example server
GET localhost:8080/api/review?id=1

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 1,
  "description": "Testowa prawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 111,
  "description": "Testowa prawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
PUT localhost:8080/api/review?id=1
Content-Type: application/json

{
  "reservationId": 19,
  "description": "Testowa prawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
DELETE localhost:8080/api/review?id=1