### GET request to example server
GET localhost:8080/api/reviews

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 21,
  "description": "Testowa prawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
POST localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 19,
  "description": "Testowa nieprawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
PUT localhost:8080/api/review
Content-Type: application/json

{
  "reservationId": 19,
  "description": "Testowa nieprawidlowa review",
  "rating": 5,
  "pseudonym": "janekBananek"
}

###
DELETE localhost:8080/api/reviews?id=1