### GET request to example server
GET localhost:8080/api/admin/roles

###adding
POST localhost:8080/api/admin/roles
Content-Type: application/json

{
  "name": "Customer"
}

###exsisting
PUT localhost:8080/api/admin/roles?id=2
Content-Type: application/json

{
  "name": "Admin"
}

###non existing
PUT localhost:8080/api/admin/roles?id=32324
Content-Type: application/json

### exisitng
DELETE localhost:8080/api/admin/roles?id=3

### non existing
DELETE localhost:8080/api/admin/roles?id=123343

