###Get all users
GET localhost:8080/api/admin/users

###Get user by id (happy path)
GET localhost:8080/api/admin/user?id=1

###Get user by id(non existing)
GET localhost:8080/api/admin/user?id=111111

###Create user
POST localhost:8080/api/admin/user
Content-Type: application/json

{
  "name": "Amanda",
  "surname": "Preisner",
  "phone": "123-456-789",
  "email": "amanda@wp.pl",
  "roles": [
    {"id": 1}
  ]

}

###Update existing user
PUT localhost:8080/api/admin/user?id=2
Content-Type: application/json

{
  "name": "Amanda",
  "surname": "Preisner",
  "phone": "123-456-789",
  "email": "dddddd@wp.pl",
  "roles": [
    {"id": 3}
  ]
}

###Update non-existing user
PUT localhost:8080/api/admin/user?id=2322
Content-Type: application/json

{
  "name": "Amanda",
  "surname": "Preisner",
  "phone": "123-456-789",
  "email": "amandddda@wp.pl",
  "roles": [
    {"id": 3}
  ]
}

###Delete existing
DELETE localhost:8080/api/admin/user?id=2

###Delete non existing
DELETE localhost:8080/api/admin/user?id=14454





