name: Build & Push Docker image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/pl_car-rental_final-project
          DATE_TAG=$(date +'%Y-%m-%d')
          COMMIT_TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          VERSION_TAG="${DATE_TAG}-${COMMIT_TAG}"

          echo "Building image with tags: latest and ${VERSION_TAG}"

          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${VERSION_TAG} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/pl_car-rental_final-project
          DATE_TAG=$(date +'%Y-%m-%d')
          COMMIT_TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          VERSION_TAG="${DATE_TAG}-${COMMIT_TAG}"

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${VERSION_TAG}
